// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJBaZoI7BR-MeXtnGcgrMDY31HXZQ4vI',
    appId: '1:442845057720:web:95204a1dabdeb07c071a4d',
    messagingSenderId: '442845057720',
    projectId: 'project1-48f32',
    authDomain: 'project1-48f32.firebaseapp.com',
    storageBucket: 'project1-48f32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfwFClvu3AjyanrTyIqsOi-2GaSBpw44k',
    appId: '1:442845057720:android:e27fd6e03dc2eb08071a4d',
    messagingSenderId: '442845057720',
    projectId: 'project1-48f32',
    storageBucket: 'project1-48f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufdABwg4jdp2QTafDIs2PQ96wATA9RlM',
    appId: '1:442845057720:ios:e1d79c19c2cacb4e071a4d',
    messagingSenderId: '442845057720',
    projectId: 'project1-48f32',
    storageBucket: 'project1-48f32.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBufdABwg4jdp2QTafDIs2PQ96wATA9RlM',
    appId: '1:442845057720:ios:e1d79c19c2cacb4e071a4d',
    messagingSenderId: '442845057720',
    projectId: 'project1-48f32',
    storageBucket: 'project1-48f32.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKJBaZoI7BR-MeXtnGcgrMDY31HXZQ4vI',
    appId: '1:442845057720:web:f79f86a460584c60071a4d',
    messagingSenderId: '442845057720',
    projectId: 'project1-48f32',
    authDomain: 'project1-48f32.firebaseapp.com',
    storageBucket: 'project1-48f32.appspot.com',
  );
}
